language: php

php:
  - "7.2"

dist: trusty

cache:
  directories:
    - $HOME/.composer/cache/files # Composer files

before_script:
  # Application setup
  - composer self-update
  - composer install --dev --no-interaction
  - cp .env.test .env
  - cp phpcs.xml.local phpcs.xml

script:
  - ./vendor/bin/phpcs --standard=phpcs.xml